/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECTerminal */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECTerminal
#define _Included_info_cerios_electrocraft_core_computer_XECTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECTerminal
 * Method:    getLine
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_cerios_electrocraft_core_computer_XECTerminal_getLine
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECTerminal
 * Method:    getColoumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_cerios_electrocraft_core_computer_XECTerminal_getColoumns
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECTerminal
 * Method:    getRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_info_cerios_electrocraft_core_computer_XECTerminal_getRows
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECTerminal
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECTerminal_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
