/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECCPU */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECCPU
#define _Included_info_cerios_electrocraft_core_computer_XECCPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    getVideoCard
 * Signature: ()Linfo/cerios/electrocraft/core/computer/XECVGACard;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_getVideoCard
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    getTerminal
 * Signature: ()Linfo/cerios/electrocraft/core/computer/XECTerminal;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_getTerminal
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    getKeyboard
 * Signature: ()Linfo/cerios/electrocraft/core/computer/XECKeyboard;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_getKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    assemble
 * Signature: (Ljava/lang/String;)Linfo/cerios/electrocraft/core/computer/XECInterface/AssembledData;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_assemble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    loadIntoMemory
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_loadIntoMemory
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    manualTick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_manualTick
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_stop
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    isRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_isRunning
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    registerInterupt
 * Signature: (ILinfo/cerios/electrocraft/core/computer/IComputerCallback;)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_registerInterupt
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECCPU
 * Method:    removeInterupt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECCPU_removeInterupt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
