/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECInterface */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECInterface
#define _Included_info_cerios_electrocraft_core_computer_XECInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    createCPU
 * Signature: (IIIIIIJ)Linfo/cerios/electrocraft/core/computer/XECCPU;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_createCPU
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
