/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECCPU_InteruptData */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECCPU_InteruptData
#define _Included_info_cerios_electrocraft_core_computer_XECCPU_InteruptData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
