/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECKeyboard */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECKeyboard
#define _Included_info_cerios_electrocraft_core_computer_XECKeyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECKeyboard
 * Method:    onKeyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECKeyboard_onKeyPress
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
