/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECVGACard */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECVGACard
#define _Included_info_cerios_electrocraft_core_computer_XECVGACard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECVGACard
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECVGACard_clearScreen
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECVGACard
 * Method:    getScreenData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_info_cerios_electrocraft_core_computer_XECVGACard_getScreenData
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECVGACard
 * Method:    setScreenSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECVGACard_setScreenSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECVGACard
 * Method:    manualTick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECVGACard_manualTick
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
