/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_cerios_electrocraft_core_computer_XECInterface */

#ifndef _Included_info_cerios_electrocraft_core_computer_XECInterface
#define _Included_info_cerios_electrocraft_core_computer_XECInterface
#pragma GCC visibility push(default)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    createCPU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_createCPU
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    assemble
 * Signature: (Ljava/lang/String;)Linfo/cerios/electrocraft/core/computer/XECInterface/AssembledData;
 */
JNIEXPORT jobject JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_assemble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    execMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_execMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    loadIntoMemory
 * Signature: ([Ljava/lang/Byte;I)J
 */
JNIEXPORT jlong JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_loadIntoMemory
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_stop
  (JNIEnv *, jobject);

/*
 * Class:     info_cerios_electrocraft_core_computer_XECInterface
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_info_cerios_electrocraft_core_computer_XECInterface_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#pragma GCC visibility pop
#endif
